# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-17 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20160312_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagproject',
            name='order',
            field=models.IntegerField(default=0, verbose_name=b'\xd0\xa1\xd0\xbe\xd1\x80\xd1\x82\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb0'),
        ),
    ]
