version: '2'
services:
  db:
    image: postgres:9.5
  web:
    build: .
    image: eliseev_django
    command: ./run.sh
    volumes:
      - .:/code
    depends_on:
      - db
  nginx:
    image: nginx
    volumes:
      - ./nginx_conf.conf:/etc/nginx/conf.d/default.conf
      - ./:/code/
    ports:
      - "8000:80"
    depends_on:
      - web