# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-11 12:45
from __future__ import unicode_literals
from django.db import migrations


def init_template_page(apps, schema_editor):
    Page = apps.get_model("pages", "Page")
    Page.objects.update(template='page.html')
    Page.objects.filter(url='/').update(template='2016/main.html')
    pages = (
        {
            'url': 'proektirovanie-domov',
            'h1': u'Архитектурное проектирование домов',
            'name': u'Архитектурное проектирование домов',
            'title': u'Архитектурное проектирование домов',
            'body': u'<p>Создаем дома, которые делают вас счастливыми</p>',
            'template': '2016/architectural-design.html',
        },
        {
            'url': 'stroitelstvo',
            'h1': u'Строительство домов и коттеджей',
            'name': u'Строительство домов и коттеджей',
            'title': u'Строительство домов и коттеджей',
            'body': u'<p>Создаем дома, которые делают вас счастливыми</p>',
            'template': '2016/building.html',
         },
        {
            'url': 'dizain',
            'h1': u'Дизайн интерьера',
            'name': u'Дизайн интерьера',
            'title': u'Дизайн интерьера',
            'body': u'<p>Создаем интерьеры для жизни</p>',
            'template': '2016/interior-design.html',
        },
        {
            'url': 'why-we',
            'h1': u'Почему мы',
            'name': u'Почему мы',
            'title': u'Почему мы',
            'body': u'<p>Красивые дома сами собой не получаются. Без талантливого архитектора получается либо унылая однотипная застройка, либо аляпистая безвкусица. Не думаю, что это то, о чем вы мечтаете.</p> <p>Я делаю дома такими, какими я их чувствую. Чтобы почувствовать дом, мне нужно понять и примерить на себя стиль жизни заказчика, его привычки, стать на короткий момент времени частым гостем в этом создаваемом доме. Только тогда, когда ты станешь другом своего заказчика, ты сможешь создать дом именно для этой семьи, с ее ценностями и традициями.</p>',
            'template': '2016/why-we.html',
        }
    )
    for page in pages:
        Page.objects.filter(url=page['url']).delete()
        obj, created = Page.objects.get_or_create(**page)
        if created:
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_page_template'),
    ]

    operations = [
        migrations.RunPython(init_template_page, reverse_code=migrations.RunPython.noop),
    ]
