# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-15 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(blank=True, default=b'page.html', max_length=255, verbose_name=b'\xd0\xa8\xd0\xb0\xd0\xb1\xd0\xbb\xd0\xbe\xd0\xbd'),
        ),
    ]
