# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-16 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20161115_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkLanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h2', models.CharField(blank=True, max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('body', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('key', models.CharField(max_length=255, verbose_name='\u041a\u043b\u044e\u0447')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430')),
            ],
            options={
                'verbose_name': '\u041e\u0441\u0442\u0440\u043e\u0432\u043e\u043a \u0442\u0435\u043a\u0441\u0442\u0430',
                'verbose_name_plural': '\u041e\u0441\u0442\u0440\u043e\u0432\u043a\u0438 \u0442\u0435\u043a\u0441\u0442\u0430',
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[(b'left', b'\xd0\xa1\xd0\xbb\xd0\xb5\xd0\xb2\xd0\xb0'), (b'right', b'\xd0\xa1\xd0\xbf\xd1\x80\xd0\xb0\xd0\xb2\xd0\xb0')], default=b'right', max_length=10, verbose_name='\u041f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='\u0421\u043e\u0440\u0442\u0438\u0440\u043e\u0432\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0431\u0430\u043d\u043d\u0435\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title2',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435, \u0432\u0442\u043e\u0440\u0430\u044f \u0441\u0442\u0440\u043e\u043a\u0430'),
        ),
    ]
