# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-16 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_create_island_chunk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunklanding',
            options={'ordering': ('key',), 'verbose_name': '\u041e\u0441\u0442\u0440\u043e\u0432\u043e\u043a \u0442\u0435\u043a\u0441\u0442\u0430', 'verbose_name_plural': '\u041e\u0441\u0442\u0440\u043e\u0432\u043a\u0438 \u0442\u0435\u043a\u0441\u0442\u0430'},
        ),
        migrations.AlterField(
            model_name='chunklanding',
            name='key',
            field=models.CharField(max_length=255, unique=True, verbose_name='\u041a\u043b\u044e\u0447'),
        ),
    ]
