# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-16 07:28
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20161116_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunklanding',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
