# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-17 08:21
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    import os
    from django.conf import settings
    from shutil import copy2
    from pwd import getpwnam
    Page = apps.get_model("pages", "Page")
    ParralaxImage = apps.get_model('pages', 'ParralaxImage')
    data = (
        {
            'url': u'/',
            'image': {
                'img': u'2016/images/ilya.jpg',
                'key': 'ie',
            }
        },
        {
            'url': u'/',
            'image': {
                'img': u'2016/images/first-bg.jpg',
                'key': 'index1',
            }
        },
        {
            'url': u'/',
            'image': {
                'img': u'2016/images/counters-bg.jpg',
                'key': 'index2',
            }
        },
        {
            'url': u'/',
            'image': {
                'img': u'2016/images/ban-bg.jpg',
                'key': 'index3',
            }
        },
        {
            'url': u'/',
            'image': {
                'img': u'2016/images/ban-bg.jpg',
                'key': 'index4',
            }
        },
        {
            'url': u'/',
            'image': {
                'img': u'2016/images/feedback-bg.jpg',
                'key': 'feedback',
            }
        },
        {
            'url': u'proektirovanie-domov',
            'image': {
                'img': u'2016/images/page-header_arch-bg.jpg',
                'key': 'proekt1',
            }
        },
        {
            'url': u'proektirovanie-domov',
            'image': {
                'img': u'2016/images/ilya.jpg',
                'key': 'pie',
            }
        },
        {
            'url': u'proektirovanie-domov',
            'image': {
                'img': u'2016/images/ban-bg.jpg',
                'key': 'proekt2',
            }
        },
        {
            'url': u'proektirovanie-domov',
            'image': {
                'img': u'2016/images/steps-bg.jpg',
                'key': 'proekt3',
            }
        },
        {
            'url': u'dizain',
            'image': {
                'img': u'2016/images/page-header_int-bg.jpg',
                'key': 'dizain1',
            }
        },
        {
            'url': u'dizain',
            'image': {
                'img': u'2016/images/ban-bg.jpg',
                'key': 'dizain2',
            }
        },
        {
            'url': u'dizain',
            'image': {
                'img': u'2016/images/steps-bg.jpg',
                'key': 'dizain3',
            }
        },
        {
            'url': u'dizain',
            'image': {
                'img': u'2016/images/ilya.jpg',
                'key': 'die',
            }
        },
        {
            'url': u'stroitelstvo',
            'image': {
                'img': u'2016/images/page-header_arch-bg.jpg',
                'key': 'stroitelstvo1',
            }
        },
        {
            'url': u'stroitelstvo',
            'image': {
                'img': u'2016/images/ban-bg.jpg',
                'key': 'stroitelstvo2',
            }
        },
        {
            'url': u'stroitelstvo',
            'image': {
                'img': u'2016/images/ban-bg.jpg',
                'key': 'stroitelstvo3',
            }
        },
        {
            'url': u'stroitelstvo',
            'image': {
                'img': u'2016/images/steps-bg.jpg',
                'key': 'stroitelstvo4',
            }
        },
        {
            'url': u'stroitelstvo',
            'image': {
                'img': u'2016/images/ilya.jpg',
                'key': 'sie',
            }
        },
        {
            'url': u'why-we',
            'image': {
                'img': u'2016/images/secret-bg.jpg',
                'key': 'whywe1',
            }
        },
        {
            'url': u'why-we',
            'image': {
                'img': u'2016/images/scheme-bg.jpg',
                'key': 'whywe2',
            }
        },
    )
    dst_dir = os.path.join(settings.MEDIA_ROOT, 'images_p')
    try:
        os.makedirs(dst_dir)
        user = getpwnam('www-data').pw_uid
        group = getpwnam('www-data').pw_gid
        os.chown(dst_dir, user, group)
    except OSError:
        pass
    ParralaxImage.objects.all().delete()

    for img in data:
        src = os.path.join(settings.BASE_DIR, 'static/%s' % img['image']['img'])
        filename = os.path.split(img['image']['img'])[1]
        dst = os.path.join(dst_dir, filename)
        copy2(src, dst)
        try:
            os.chown(dst, user, group)
        except:
            pass
        try:
            page = Page.objects.get(url=img['url'])
        except Page.DoesNotExist:
            print('\nDoes not exist %s' % img['url'])
            continue
        except Page.MultipleObjectsReturned:
            print('Drop page %s' % img['url'])
            continue
        ParralaxImage.objects.create(page=page, img='images_p/%s' % filename, key=img['image']['key'])


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20161117_1243'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
    ]
