# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-17 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_slider_parralax'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='alt',
            field=models.CharField(blank=True, default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, default=True, max_length=255),
        ),
    ]
