# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-17 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20161116_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParralaxImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', sorl.thumbnail.fields.ImageField(upload_to=b'images_p/', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='\u041a\u043b\u044e\u0447')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430')),
            ],
            options={
                'ordering': ('key',),
                'verbose_name': '\u041f\u0430\u0440\u0430\u043b\u043b\u0430\u043a\u0441',
                'verbose_name_plural': '\u041f\u0430\u0440\u0430\u043b\u043b\u0430\u043a\u0441',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', sorl.thumbnail.fields.ImageField(upload_to=b'images_s/', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
                ('sort', models.IntegerField(default=200, verbose_name=b'\xd0\xa1\xd0\xbe\xd1\x80\xd1\x82\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb0')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430')),
            ],
            options={
                'ordering': ('sort',),
                'verbose_name': '\u0421\u043b\u0430\u0439\u0434\u0435\u0440',
                'verbose_name_plural': '\u0421\u043b\u0430\u0439\u0434\u0435\u0440',
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['sort'], 'verbose_name': '\u0422\u043e \u0447\u0442\u043e \u043c\u044b \u043b\u044e\u0431\u0438\u043c/\u0431\u0430\u043d\u043d\u0435\u0440', 'verbose_name_plural': '\u0422\u043e \u0447\u0442\u043e \u043c\u044b \u043b\u044e\u0431\u0438\u043c/\u0431\u0430\u043d\u043d\u0435\u0440\u044b'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[(b'love', '\u0422\u043e \u0447\u0442\u043e \u043c\u044b \u043b\u044e\u0431\u0438\u043c'), (b'left', '\u0421\u043b\u0435\u0432\u0430'), (b'right', '\u0421\u043f\u0440\u0430\u0432\u0430')], default=b'right', max_length=10, verbose_name='\u041f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
