# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-17 17:42
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Page = apps.get_model("pages", "Page")
    Staff = apps.get_model("pages", "Staff")
    try:
        page = Page.objects.get(url='why-we')
    except Page.DoesNotExist:
        return
    for staff in Staff.objects.all():
        staff.page.add(page)


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_staff_page'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
    ]
