# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-17 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_add_many_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='page',
            field=models.ManyToManyField(default=(1,), to='pages.Page', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430'),
        ),
    ]
