# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-17 18:19
from __future__ import unicode_literals
from django.db import migrations


def forwards(apps, schema_editor):
    Page = apps.get_model("pages", "Page")
    Page.objects.filter(url='otzyvi').update(template='2016/feedbacks.html', body='<p></p>')
    ParralaxImage = apps.get_model('pages', 'ParralaxImage')
    try:
        page = Page.objects.get(url='otzyvi')
        ParralaxImage.objects.create(key='feedback1', page=page, img='images_p/first-bg.jpg')
    except:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20161117_2101'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
    ]
