# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-18 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_feedback_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('descr', models.TextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('price', models.IntegerField(default=0, verbose_name='\u0426\u0435\u043d\u0430')),
                ('sort', models.IntegerField(default=0, verbose_name='\u0421\u043e\u0440\u0442\u0438\u0440\u043e\u0432\u043a\u0430')),
                ('page', models.ManyToManyField(to='pages.Page', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430')),
            ],
            options={
                'ordering': ('sort',),
                'verbose_name': '\u0426\u0435\u043d\u0430',
                'verbose_name_plural': '\u0426\u0435\u043d\u044b',
            },
        ),
    ]
