# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-18 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='page',
        ),
    ]
