# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-18 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_remove_price_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430'),
            preserve_default=False,
        ),
    ]
