# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-19 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='descr',
            field=models.CharField(default='', max_length=255, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
            preserve_default=False,
        ),
    ]
