# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-19 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_settings_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='flash',
            field=models.FileField(blank=True, upload_to=b'flash_settings', verbose_name='\u0424\u043b\u0435\u0448\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='descr',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='key',
            field=models.CharField(choices=[(b'flash1', '\u0424\u043b\u0435\u0448\u043a\u0430 \u0434\u043b\u044f \u043f\u0440\u043e\u0435\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f \u0434\u043e\u043c\u043e\u0432'), (b'flash2', '\u0424\u043b\u0435\u0448\u043a\u0430 \u0434\u043b\u044f \u0438\u043d\u0442\u0435\u0440\u044c\u0435\u0440\u043e\u0432'), (b'50px', '\u041f\u0430\u0440\u0430\u043b\u043b\u0430\u043a\u0441 50px'), (b'-50px', '\u041f\u0430\u0440\u0430\u043b\u043b\u0430\u043a\u0441 -50px')], max_length=20, verbose_name='\u041a\u043b\u044e\u0447'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
    ]
