# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-23 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20161120_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='\u0412\u044b\u0441\u043e\u0442\u0430 261px, \u0448\u0438\u0440\u0438\u043d\u0430 403px', null=True, upload_to=b'images_a/', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[(b'love', '\u0422\u043e \u0447\u0442\u043e \u043c\u044b \u043b\u044e\u0431\u0438\u043c'), (b'left', '\u0421\u043b\u0435\u0432\u0430'), (b'right', '\u0421\u043f\u0440\u0430\u0432\u0430')], default=b'love', max_length=10, verbose_name='\u041f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
