# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-01 13:08
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_remove_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='\u0412\u044b\u0441\u043e\u0442\u0430 266px, \u0448\u0438\u0440\u0438\u043d\u0430 380px', null=True, upload_to=b'images_a/', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
    ]
