# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-08 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_auto_20161201_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.CharField(blank=True, max_length=15, verbose_name='\u0414\u0430\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='video_url',
            field=models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f'),
        ),
    ]
