# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-08 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_auto_20171008_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='\u0414\u0430\u0442\u0430'),
        ),
    ]
