# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-15 07:47
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_auto_20171008_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=b'images_feedback/', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
    ]
