# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-18 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_feedback_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='form_header',
            field=models.CharField(blank=True, max_length=500, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba \xd0\xbe\xd0\xba\xd0\xbe\xd0\xbb\xd0\xbe \xd1\x84\xd0\xbe\xd1\x80\xd0\xbc\xd1\x8b'),
        ),
        migrations.AddField(
            model_name='page',
            name='form_text',
            field=models.TextField(blank=True, verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xba\xd1\x81\xd1\x82 \xd0\xbe\xd0\xba\xd0\xbe\xd0\xbb\xd0\xbe \xd1\x84\xd0\xbe\xd1\x80\xd0\xbc\xd1\x8b'),
        ),
    ]
