# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 19:36
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('buildhouse', '0010_articletag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='descr',
            field=tinymce.models.HTMLField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
