# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildhouse', '0011_auto_20160208_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletag',
            name='tag',
            field=models.ForeignKey(blank=True, help_text=b'\xd0\x95\xd1\x81\xd0\xbb\xd0\xb8 \xd0\xbd\xd0\xb5 \xd0\xb2\xd1\x8b\xd0\xb1\xd1\x80\xd0\xb0\xd1\x82\xd1\x8c \xd1\x82\xd0\xb5\xd0\xb3, \xd1\x82\xd0\xbe \xd1\x81\xd1\x82\xd0\xb0\xd1\x82\xd1\x8c\xd1\x8f \xd0\xbf\xd0\xbe\xd1\x8f\xd0\xb2\xd0\xb8\xd1\x82\xd1\x81\xd1\x8f \xd0\xb2 \xd0\xbf\xd1\x80\xd0\xbe\xd0\xb5\xd0\xba\xd1\x82\xd0\xb0\xd1\x85', null=True, on_delete=django.db.models.deletion.CASCADE, to='buildhouse.Tag', verbose_name=b'\xd1\x82\xd0\xb5\xd0\xb3'),
        ),
    ]
